Downgrade gunicorn to previous version because of --log-syslog error
Regression in latest 19.8 release of gunicorn

AttributeError: No configuration setting for: disable_access_log_redirection